### ISSUE TITLE
Compile time error Is there an instructional video

### ISSUE THREAD

**Issue by kk159963** [Tugamer89/RansomTuga#1]
![螢幕擷取畫面 2022-11-07 014349](https://user-images.githubusercontent.com/103036062/200186424-dcc221a4-6bc4-486c-8ce9-a459729d7683.png)

**Comment by Tugamer89** [comment]
You should change the value of `TrojanFileContent` in RansomTuga/main.cpp line 10 to a valid file location in your pc
or disable `DROPRUN_TROJAN_FILE` in commons/common.h line 45 to `false`
