### ISSUE TITLE
"I have an error while compiling

### ISSUE THREAD

**Issue by ruvt4r** [Tugamer89/RansomTuga#3]
![error](https://user-images.githubusercontent.com/111100686/227809424-f896edd4-cbcd-42ed-b78d-83c08fa595c6.PNG)

**Comment by Tugamer89** [comment]
Can you give more info about what you did?
Be sure the `RansomTuga/preCompilation.tmp` file is present after precompilation

**Comment by ruvt4r** [comment]
I can't find the /preCompilation.tmp file. I have downloaded the code again, but it's still missing. I think it's not included in the code."

**Comment by ruvt4r** [comment]
I had another error with the postCompilation.bat, but I fixed it. However, the preCompilation.tmp file is nowhere to be found. Any ideas?"

**Comment by Tugamer89** [comment]
That file is generated after precompilation and is deleted after postcompilation

**Comment by ruvt4r** [comment]
For some reason, the file is not being generated or is not being set in the correct path. What can I do to check what's happening with the file?"
![error2](https://user-images.githubusercontent.com/111100686/228327165-53566141-24c6-4554-9272-f58d2bd63573.PNG)

**Comment by Tugamer89** [comment]
run first `preComp.py` and check if the file is present, then run `postComp.py`

**Comment by ruvt4r** [comment]
"I ran it, but still, the file is not appearing."
![errro3](https://user-images.githubusercontent.com/111100686/228368581-fefd22df-182b-4ece-9c1d-c52410b7589e.PNG)

**Comment by Tugamer89** [comment]
Install pyrcryptodome using `pip install pycryptodome`

**Comment by ruvt4r** [comment]
The library is already installed, what else could be causing problems?"

**Comment by Tugamer89** [comment]
Look these lines: https://github.com/Tugamer89/RansomTuga/blob/master/RansomTuga/preComp.py#L8-L13

The only possible error is you not having installed pyrcryptodome. Are you sure you have installed it in the correct version of python?

**Comment by Tugamer89** [comment]
Have you fixed it? I'll close this issue in 24 hrs if no response

**Comment by ruvt4r** [comment]
"I deleted everything, reinstalled it, and I still have the same error."

**Comment by Tugamer89** [comment]
If the error still persists, write these lines in the Python shell and see what errors you get
` from Cryptodome.Cipher import AES
from Cryptodome.Util.Padding import pad`

**Comment by NoOne1979** [comment]
Hello! I currently have the same problem, how did you resolve?
