### ISSUE TITLE
About file encryption

### ISSUE THREAD

**Issue by livetrx** [Tugamer89/RansomTuga#4]
The program only encrypts the user folder. Can you update it to encrypt all attached disks and files? Telegram bot is not working and also turned off sending mail with gmail 587. There may be options for that as well. Finally, the information file is sent by e-mail, in case there are too many files, the file will grow and will not fit into the e-mail attachment. Thanks.

**Comment by Tugamer89** [comment]
I just added an array containing all the folders you want to encrypt (it also works with different disks) [here](https://github.com/Tugamer89/RansomTuga/blob/master/commons/common.h#L106).
As soon as possible I will also add a function that allows you to encrypt all files on all drives other than `C:/`.
