### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by Charles2333** [Tugamer89/RansomTuga#8]
Why don't you have these header files and need to write them yourself? How do you define them?
![image](https://github.com/Tugamer89/RansomTuga/assets/40413481/fdc5f799-bebe-4ffd-b30f-5e6df86de4b4)

**Comment by Tugamer89** [comment]
You have to install the dependencies

**Comment by Charles2333** [comment]
Install these dependencies? This is more like my own file. What dependencies do we need to install?

**Comment by Tugamer89** [comment]
You need to install CryptoPP and minhook, look at [here](https://github.com/Tugamer89/RansomTuga#Compilation-Instructions)
